Distribuerade-System-Labb-2/Models/GroupViewModel.cs
using Distribuerade_System_Labb_2.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Distribuerade_System_Labb_2.Models
{
    public class GroupViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please enter a group title")]
        [StringLength(60, MinimumLength = 3)]
        public string GroupTitle { get; set; }
        public string OwnerId { get; set; }
        public virtual List<GroupMemberViewModel> MemberIds { get; set; }
    }
}

Distribuerade-System-Labb-2/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Distribuerade_System_Labb_2.Models;
using Microsoft.AspNetCore.Identity;
using Distribuerade_System_Labb_2.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using BusinessLogic.GroupLogic;
using BusinessLogic.MessageLogic;
using System.Diagnostics;

namespace Distribuerade_System_Labb_2.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private readonly GroupLogic groupLogic = new GroupLogic();
        private readonly MessageLogic messageLogic = new MessageLogic();
        private readonly Distribuerade_System_Labb_2Context _context;
        private readonly UserManager<Distribuerade_System_Labb_2User> _userManager;

        public GroupsController(Distribuerade_System_Labb_2Context context, UserManager<Distribuerade_System_Labb_2User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        /// <summary>
        /// GET INDEX
        /// </summary>
        /// <returns>Conversations</returns>
        public async Task<IActionResult> Index()
        {
            Distribuerade_System_Labb_2User currentUser = await _userManager.GetUserAsync(User);
            List<GroupViewModel> groups = await GetAllGroups(currentUser.Id);
            return View(groups);
        }

        /// <summary>
        /// GET All groups of user logged in 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> MyGroups()
        {
            Distribuerade_System_Labb_2User currentUser = await _userManager.GetUserAsync(User);
            List<GroupViewModel> groups = await GetAllMyOwnedGroups(currentUser.Id);
            return View(groups);
        }

        /// <summary>
        /// GET List of joined groups
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> JoinedGroup()
        {
            Distribuerade_System_Labb_2User currentUser = await _userManager.GetUserAsync(User);
            List<GroupViewModel> groups = await GetAllJoinedGroup(currentUser.Id);
            return View(groups);
        }


       /// <summary>
       /// GET Create group page
       /// </summary>
       /// <returns></returns>
        public IActionResult CreateGroup()
        {
            return View();
        }

        /// <summary>
        /// POST new group
        /// </summary>
        /// <param name="group">group model</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateGroup([Bind("GroupTitle")] GroupViewModel group)
        {
            Distribuerade_System_Labb_2User currentUser = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                int result = await groupLogic.CreateNewGroup(group.GroupTitle, currentUser.Id);
                TempData["ConfirmationMessage"] = "Group: " + group.GroupTitle + " was created!";
                return RedirectToAction("CreateGroup");
            }
            return RedirectToAction("CreateGroup");
        }

        /// <summary>
        /// GET SendMessagePage details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> SendGroupMessage(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            int groupId = id ?? default(int);

            List <GroupMemberViewModel> listOfGroupMembers = await GetAllMembersOfGroup(groupId);
            List<Distribuerade_System_Labb_2User> userList = await MemberToUserList(listOfGroupMembers);
            var usernameList = new SendMessageViewModel();
            usernameList.Values = userList.Select((u, index) => new SelectListItem { Value = u.Id, Text = u.UserName, Selected = true });
            return View(usernameList);
        }

        /// <summary>
        /// POST Sends messages to multiple users
        /// </summary>
        /// <param name="sendMessageViewModel">sendmessage model</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendGroupMessage([Bind("TitleMessage,Body,SelectedValues")] SendMessageViewModel sendMessageViewModel)
        {
            Distribuerade_System_Labb_2User currentUser = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                List<string> usersSentTo = new List<string>();
                int result = 0;
                foreach (var u in sendMessageViewModel.SelectedValues)
                {
                    sendMessageViewModel.ReceiverId = u;
                    usersSentTo.Add(GetUserById(sendMessageViewModel.ReceiverId).UserName);
                    result = await messageLogic.CreateNewMessage(sendMessageViewModel.TitleMessage, sendMessageViewModel.Body, sendMessageViewModel.ReceiverId, currentUser.Id);
                }
                TempData["ConfirmationMessage"] = "Grupp meddelande  avsänt till "
                   + String.Join(", ", usersSentTo.ToArray()) + ", " + DateTime.Now.ToString("HH:mm yyyy-MM-dd");
                return RedirectToAction("CreateGroup");
            }
            return RedirectToAction("CreateGroup");
        }

        /// <summary>
        /// GET Join group page
        /// </summary>
        /// <param name="id">Id of group</param>
        /// <returns></returns>
        public async Task<IActionResult> JoinGroup(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            int groupId = id ?? default(int);
            Distribuerade_System_Labb_2User currentUser = await _userManager.GetUserAsync(User);
            bool result = await groupLogic.RegisterToGroup(groupId, currentUser.Id);
            return RedirectToAction("Index");

        }

        /// <summary>
        /// Members To User Mapping
        /// </summary>
        /// <param name="memberList">model</param>
        /// <returns></returns>
        private async Task<List<Distribuerade_System_Labb_2User>> MemberToUserList(List<GroupMemberViewModel> memberList)
        {
            List<Distribuerade_System_Labb_2User> userList = new List<Distribuerade_System_Labb_2User>();
            foreach (var m in memberList)
            {
                
                userList.Add(GetUserById(m.UserId));
            }
            return userList;
        }
        /// <summary>
        /// Gets User by id
        /// </summary>
        /// <param name="id">id of user</param>
        /// <returns></returns>
        private Distribuerade_System_Labb_2User GetUserById(String id)
        {
            return _context.Users.Find(id);
        }

        /// <summary>
        /// Gets all members of a group
        /// </summary>
        /// <param name="groupId">group id</param>
        /// <returns></returns>
        private async Task<List<GroupMemberViewModel>> GetAllMembersOfGroup(int groupId)
        {
            List<GroupMemberViewModel> groupMemberList = new List<GroupMemberViewModel>();
            var members = await groupLogic.GetAllMembersOfGroup(groupId);
            if (members.Count > 0)
            {
                foreach (var m in members)
                {
                    GroupMemberViewModel currentMember = new GroupMemberViewModel
                    {
                        Id = m.Id,
                        UserId = m.UserId

                    };
                    groupMemberList.Add(currentMember);
                }
            }
            return groupMemberList;
        }


        private async Task<List<GroupViewModel>> GetAllGroups(string userId)
        {
            List<GroupViewModel> groupList = new List<GroupViewModel>();
            List<GroupMemberViewModel> groupMembers = new List<GroupMemberViewModel>();
            var groups = await groupLogic.GetAllGroups(userId);
            if (groups.Count > 0)
            {
                foreach (var g in groups)
                {
                    if(g.Members != null)
                    {
                        foreach (var gMember in g.Members)
                        {
                            GroupMemberViewModel currentMember = new GroupMemberViewModel
                            {
                                Id = gMember.Id,
                                UserId = gMember.UserId
                            };
                            if(g.Id == gMember.GroupId)
                            groupMembers.Add(currentMember);
                        }
                        GroupViewModel currentGroup = new GroupViewModel
                        {
                            Id = g.Id,
                            GroupTitle = g.GroupTitle,
                            OwnerId = g.OwnerId,
                            MemberIds = groupMembers

                        };
                        groupList.Add(currentGroup);
                    }
                    else
                    {
                        GroupViewModel currentGroup = new GroupViewModel
                        {
                            Id = g.Id,
                            GroupTitle = g.GroupTitle,
                            OwnerId = g.OwnerId,
                        };
                        groupList.Add(currentGroup);
                    }
                }
            }
            return groupList;
        }

        private async Task<List<GroupViewModel>> GetAllJoinedGroup(string userId)
        {
            List<GroupViewModel> groupList = new List<GroupViewModel>();
            List<GroupMemberViewModel> groupMembers = new List<GroupMemberViewModel>();

Distribuerade-System-Labb-2/Views/Groups/CreateGroup.cshtml
@model Distribuerade_System_Labb_2.Models.GroupViewModel

@{
    ViewData["Title"] = "CreateGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Group Details</h4>
<hr />
<div class="row">
    @using (Html.BeginForm("CreateGroup", "Groups", FormMethod.Post))
    {
        <div class="col-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="GroupTitle" name="GroupTitle" class="control-label">Group title</label>
                    @Html.TextBox("GroupTitle")
                    <span asp-validation-for="GroupTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
            @if (TempData["ConfirmationMessage"] != null)
            {
                <div class="alert alert-success">@TempData["ConfirmationMessage"]</div>
            }
        </div>
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Distribuerade-System-Labb-2/Views/Groups/Index.cshtml
@model IEnumerable<Distribuerade_System_Labb_2.Models.GroupViewModel>

@{
    ViewData["Title"] = "All Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Groups</h1>

<p>
    <a asp-action="CreateGroup">Create New Group</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerId)
                </td>
                <td>
                    <a asp-action="JoinGroup" asp-route-id="@item.Id">Join group</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

Distribuerade-System-Labb-2/Views/Groups/JoinedGroup.cshtml
@model IEnumerable<Distribuerade_System_Labb_2.Models.GroupViewModel>

@{
    ViewData["Title"] = "JoinedGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h1>Joined Groups</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerId)
                </td>
            </tr>
        }
    </tbody>
</table>

Distribuerade-System-Labb-2/Views/Groups/MyGroups.cshtml
@model IEnumerable<Distribuerade_System_Labb_2.Models.GroupViewModel>

@{
    ViewData["Title"] = "MyGroups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="MyGroups">MyGroups</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerId)
                </td>
                <td>
                    <a asp-action="SendGroupMessage" asp-route-id="@item.Id">Send a message</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

Distribuerade-System-Labb-2/Views/Groups/SendGroupMessage.cshtml
@model Distribuerade_System_Labb_2.Models.SendMessageViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Group Message</h1>

<h4>Compose a message for the group users</h4>
<hr />
 @using (Html.BeginForm("SendGroupMessage", "Groups", FormMethod.Post))
    {

        <div class="messages"></div>

        <div class="controls">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TitleMessage" name="Title">Title *</label>
                        <input asp-for="TitleMessage" id="TitleMessage" type="text" name="TitleMessage" class="form-control" placeholder="Please enter a title *" required="required">
                        <span asp-validation-for="TitleMessage" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="SelectedValues" class="control-label">Select people to send to</label>
                        @Html.DropDownListFor(x => x.SelectedValues, Model.Values, new { multiple = "true" })
                        <span asp-validation-for="SelectedValues" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Body" name="Body">Message *</label>
                        <textarea asp-for="Body" name="Body" id="Body" class="form-control" placeholder="Message for me *" rows="4" required="required" data-error="Please, leave us a message."></textarea>
                        <span asp-validation-for="SelectedValues" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <input type="submit" class="btn btn-success btn-send" value="Send message">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                </div>
            </div>
        </div>
        @if (TempData["ConfirmationMessage"] != null)
        {
            <div class="alert alert-success">@TempData["ConfirmationMessage"]</div>
        }
    }
<div>
    <a asp-action="MyGroups">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}